export const fundosColor = [
    { id:'1', nome: 'Invest Fácil Simples', cor: '#33609A' },
    { id:'2', nome: 'VIP DI FIC RF REF DI', cor: '#4C9AFE' },
    { id:'3', nome: 'Banestes R Climática', cor: '#318535' },
    { id:'4', nome: 'Banestes Dividendos FIC de FIF', cor: '#FF96BC' },
    { id:'5', nome: 'Banestes FIC de FIF Incentivados de Investimento', cor: '#2A2A2A' },
    { id:'6', nome: 'Banestes Tenax Ações FIF', cor: '#71339A' },
    { id:'7', nome: 'Banestes Tesouro FIF', cor: '#D74CFE' },
    { id:'9', nome: 'Banestes Invest Fácil FIF', cor: '#853150' },
    { id:'10', nome: 'Banestes Investidor Automático FIF', cor: '#FC5558' },
    { id:'11', nome: 'Banestes Solidez Automático FIF', cor: '#FF9844' },
    { id:'12', nome: 'Banestes Invest Public Autmático FIF', cor: '#EFFD70' },
    { id:'13', nome: 'Banestes VIP DI FIC DE FIF', cor: '#99FE4C' },
    { id:'14', nome: 'Banestes VITÓRIA 500 FIC DE FIF', cor: '#36FF9A' },
    { id:'15', nome: 'Banestes Valores FIC DE FIF', cor: '#96FFED' },
    { id:'16', nome: 'Banestes IRF-M 1 Títulos Públicos', cor: '#0084FF' },
    { id:'17', nome: 'Banestes IRF-M 1 Títulos Públicos', cor: '#742286' },
    { id:'18', nome: 'Banestes Crédito Corporativo I FIC de FIF', cor: '#000000' },
    { id:'19', nome: 'Banestes IMA-B 5 Títulos Públicos FIF', cor: '#5C5C5C' },
    { id:'20', nome: 'Banestes Institucional FIF Renda Fixa', cor: '#929719' },
    { id:'21', nome: 'Banestes Estratégia FIC de FIF Renda Fixa', cor: '#451313' },
    { id:'22', nome: 'Banestes IMA-B Títulos Públicos  FIF Renda Fixa', cor: '#09333F' },
    { id:'23', nome: 'Banestes Multiestratégia FIC de FIF Multimercado', cor: '#FFC574' },
    { id:'24', nome: 'Banestes Funses FIF Multimercado', cor: '#330196' },
];
